apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-list-dev

resources:
  - ../../base

patches:
  - path: 20-mysql-secret.yaml
  - path: 21-api-secret.yaml

images:
  - name: shopping-list-api
    newName: your-registry/shopping-list-api
    newTag: dev

commonLabels:
  environment: dev
