apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shopping-list-dev

resources:
  - ../../base
  - namespace.yaml
  - 20-mysql-sealed-secret.yaml
  - 21-api-sealed-secret.yaml

patches:
  - path: 60-api-ingress.yaml

images:
  - name: ghcr.io/jannegpriv/shopping-list-api
    newTag: main

commonLabels:
  environment: dev
